### ISSUE TITLE
Tekrar eden kodlar azaltılmalı

### ISSUE THREAD

**Issue by fatihcode** [mhmt-trk/email#1]
Tekar eden kodları tek bir class altında toparlayıp her dive iki class şeklinde verilebilir.

Renk kodları hep aynı şekilde olmalı ya hep `red`, `blue` yada `#00000`, `#ffffff` gibi.

Örnek olmsı için html ve css dosyalarını aşağıdaki şekilde yazdım. 

``` html
<div class="box box1">
....
</div>
```

```css

.box{
    text-align: center;
    font-size: 25px;
    font-weight: bold;
    padding: 25px;
    font-family: 'Courier New', Courier, monospace;
    border-radius: 25px;
    margin-bottom: 20px;
    
}

.box1{
    color: rgb(34, 31, 228);
    background-color: rgb(202, 190, 190);
}

.box2{color: rgb(235, 61, 38);
    background-color: rgb(202, 190, 190);
}

.box3{
    color: purple;
    background-color: rgb(182, 174, 174);
    text-align: right;
    padding: 10px;
    font-family: 'Parisienne', 'cursive';
}

```

Eline sağlık güzel olmuş.
